name: Go

on:
  push:
    branches: [master]
    tags:
      - "release/*"
  pull_request:
    branches: [master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Get dependencies
        run: |
          SWAGGER_VERSION=v0.23.0
          mkdir -p $HOME/bin
          curl -Lo $HOME/bin/swagger https://github.com/go-swagger/go-swagger/releases/download/${SWAGGER_VERSION}/swagger_linux_amd64 \
            && chmod +x $HOME/bin/swagger
          echo "::add-path::$HOME/bin"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install swagger-merger -g

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - run: make generate

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build
        run: |
          make building_provider

      - name: Test
        run: go test -v .
      - name: Upload Binaryies for publishing
        uses: actions/upload-artifact@v2.0.1
        with:
          name: bin
          path: ${{ github.workspace }}/bin/**

  publish_release_artefacts:
    if: github.event_name == 'push' && startsWith( github.event.push.head.ref,'release/')
    name: Publish Release Artefacts
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: bin
      - name: Display structure of downloaded files
        run: ls -R

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
